# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d12ef917b0d136bb69400df07f89b7156a6ef776761536b2360899374e0d0e27d61d5ab727e447a9df02007108862802b3f5c40251b3a95b86eba806e223cc2

test:
  secret_key_base: 2c43ecd1c564f47696d2265d40b0a18e019897615f2578dd25a6f46485043ba9e26ce5c2c38de01c76c0159e45cd5217c59b9f3bb1b1fde4d6028e33c8aaa0e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
